version: '3'

services:
  relayer-init:
    image: chainsafe/chainbridge:v1.1.5
    container_name: relayer-init
    restart: "no"
    # command: accounts import --ethereum --password {{KEYSTORE_PASSWORD}} /keys/keystore.json
    command: accounts import --privateKey {{Key}} --password {{KEYSTORE_PASSWORD}}
    volumes:
      - ./keys:/keys/
    network_mode: none
  relayer:
    image: chainsafe/chainbridge:v1.1.5
    container_name: relayer
    restart: always
    environment:
      - KEYSTORE_PASSWORD={{KEYSTORE_PASSWORD}}
    command: --config /config/config.json --verbosity info --latest --metrics --metricsPort 8000
    volumes:
      - ./config:/config
      - ./keys:/keys
    network_mode: host
    depends_on:
      - relayer-init
